# Generated by Django 6.0.5 on 2026-05-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_desc', models.TextField()),
                ('item_image', models.URLField()),
                ('item_created_at', models.DateTimeField(auto_now_add=True)),
                ('item_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
