# Generated by Django 6.0.5 on 2026-05-08 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
