# Generated by Django 6.0.5 on 2026-05-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_category_tag_alter_item_category_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
